/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yatzee1;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;


/**
 *
 * @author Eirwynn Faith Begbie
 */
public class mainframe extends javax.swing.JFrame {

    /**
     * Creates new form mainframe
     */
    public mainframe() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rollDiceButton = new javax.swing.JButton();
        die1 = new javax.swing.JLabel();
        die2 = new javax.swing.JLabel();
        die3 = new javax.swing.JLabel();
        die4 = new javax.swing.JLabel();
        die5 = new javax.swing.JLabel();
        hold1 = new javax.swing.JCheckBox();
        hold1.setEnabled(false);
        hold2 = new javax.swing.JCheckBox();
        hold2.setEnabled(false);
        hold3 = new javax.swing.JCheckBox();
        hold3.setEnabled(false);
        hold4 = new javax.swing.JCheckBox();
        hold4.setEnabled(false);
        hold5 = new javax.swing.JCheckBox();
        hold5.setEnabled(false);
        rollLabel = new javax.swing.JLabel();
        rollCount = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        nextGameButton = new javax.swing.JButton();
        nextGameButton.setEnabled(false);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setResizable(false);

        rollDiceButton.setText("Roll Dice");
        rollDiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollDiceButtonActionPerformed(evt);
            }
        });

        die1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yatzee1/six.jpg"))); // NOI18N
        die1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        die1.setPreferredSize(new java.awt.Dimension(50, 50));

        die2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yatzee1/six.jpg"))); // NOI18N
        die2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        die2.setPreferredSize(new java.awt.Dimension(50, 50));

        die3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yatzee1/six.jpg"))); // NOI18N
        die3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        die3.setPreferredSize(new java.awt.Dimension(50, 50));

        die4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yatzee1/six.jpg"))); // NOI18N
        die4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        die4.setPreferredSize(new java.awt.Dimension(50, 50));

        die5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yatzee1/six.jpg"))); // NOI18N
        die5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        die5.setPreferredSize(new java.awt.Dimension(50, 50));

        hold1.setMaximumSize(new java.awt.Dimension(21, 21));
        hold1.setMinimumSize(new java.awt.Dimension(21, 21));
        hold1.setPreferredSize(new java.awt.Dimension(21, 21));
        hold1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hold1ActionPerformed(evt);
            }
        });

        hold2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hold2ActionPerformed(evt);
            }
        });

        hold3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hold3ActionPerformed(evt);
            }
        });

        hold4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hold4ActionPerformed(evt);
            }
        });

        hold5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hold5ActionPerformed(evt);
            }
        });

        rollLabel.setText("Roll:");

        rollCount.setText("0");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Aces", null, null, null, null, null},
                {"Twos", null, null, null, null, null},
                {"Threes", null, null, null, null, null},
                {"Fours", null, null, null, null, null},
                {"Fives", null, null, null, null, null},
                {"Sixes", null, null, null, null, null},
                {"Total Score", null, null, null, null, null},
                {"Bonus", null, null, null, null, null},
                {"Total", null, null, null, null, null}
            },
            new String [] {
                "Upper Section", "Game 1", "Game 2", "Game 3", "Game 4", "Game 5"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        nextGameButton.setText("Next Game");
        nextGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextGameButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"3 of a kind", null, null, null, null, null},
                {"4 of a kind", null, null, null, null, null},
                {"Full House", null, null, null, null, null},
                {"Sm Straight", null, null, null, null, null},
                {"Lg Straight", null, null, null, null, null},
                {"Yahtzee", null, null, null, null, null},
                {"Chance", null, null, null, null, null},
                {"Yatzee bonus", null, null, null, null, null},
                {"", null, null, null, null, null},
                {"Total lw", null, null, null, null, null},
                {"Total up", null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hold1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(die1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(die2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(die3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(die4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(die5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(hold2)
                                .addGap(35, 35, 35)
                                .addComponent(hold3)
                                .addGap(35, 35, 35)
                                .addComponent(hold4)
                                .addGap(36, 36, 36)
                                .addComponent(hold5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rollLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rollCount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nextGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rollDiceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rollLabel)
                            .addComponent(rollCount)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rollDiceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextGameButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(die2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(die1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(die3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(die4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(die5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hold1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hold2)
                            .addComponent(hold3)
                            .addComponent(hold4)
                            .addComponent(hold5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollDiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollDiceButtonActionPerformed
        int min = 0;
        int max = 5;
        int count = Integer.parseInt(rollCount.getText());
        
        //enable holds
        if(count == 0){
            hold1.setEnabled(true);
            hold2.setEnabled(true);
            hold3.setEnabled(true);
            hold4.setEnabled(true);
            hold5.setEnabled(true);
        }
        
        //record and limit number of clicks
        count++;
        if(count==3){
            rollDiceButton.setEnabled(false);
            hold1.setEnabled(false);
            hold2.setEnabled(false);
            hold3.setEnabled(false);
            hold4.setEnabled(false);
            hold5.setEnabled(false);
            nextGameButton.setEnabled(true);
        }
        String strcount = Integer.toString(count);
        rollCount.setText(strcount);
        
        
        //icon vars
        ImageIcon d1 = new javax.swing.ImageIcon(getClass().getResource("/yatzee1/one.jpg"));
        ImageIcon d2 = new javax.swing.ImageIcon(getClass().getResource("/yatzee1/two.jpg"));
        ImageIcon d3 = new javax.swing.ImageIcon(getClass().getResource("/yatzee1/three.jpg"));
        ImageIcon d4 = new javax.swing.ImageIcon(getClass().getResource("/yatzee1/four.jpg"));
        ImageIcon d5 = new javax.swing.ImageIcon(getClass().getResource("/yatzee1/five.jpg"));
        ImageIcon d6 = new javax.swing.ImageIcon(getClass().getResource("/yatzee1/six.jpg"));
        ImageIcon[] icons = {d1,d2,d3,d4,d5,d6};
        
        //RANDS
        int dn1 = (int)(Math.random() * ((max - min) + 1)) + min;
        int dn2 = (int)(Math.random() * ((max - min) + 1)) + min;
        int dn3 = (int)(Math.random() * ((max - min) + 1)) + min;
        int dn4 = (int)(Math.random() * ((max - min) + 1)) + min;
        int dn5 = (int)(Math.random() * ((max - min) + 1)) + min;
        int[] rands = {dn1, dn2, dn3, dn4, dn5};
        
      
        
        
        if(!hold1.isSelected()){
            die1.setIcon(icons[dn1]);
            int dval1 = dn1;
        }
        if(!hold2.isSelected()){
            die2.setIcon(icons[dn2]);
            int dval2 = dn2;
        }
        if(!hold3.isSelected()){
            die3.setIcon(icons[dn3]);
            int dval3 = dn3;
        }
        if(!hold4.isSelected()){
            die4.setIcon(icons[dn4]);
            int dval4 = dn4;
        }
        if(!hold5.isSelected()){
            die5.setIcon(icons[dn5]);
            int dval5 = dn5;
        }
        
        
        

    }//GEN-LAST:event_rollDiceButtonActionPerformed

    private void hold1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hold1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hold1ActionPerformed

    private void hold2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hold2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hold2ActionPerformed

    private void hold3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hold3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hold3ActionPerformed

    private void hold4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hold4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hold4ActionPerformed

    private void hold5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hold5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hold5ActionPerformed

    private void nextGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextGameButtonActionPerformed
        //reset rollcount/buttons
        rollCount.setText("0");
        rollDiceButton.setEnabled(true);
        
        //reset hold buttons
        hold1.setSelected(false);
        hold2.setSelected(false);
        hold3.setSelected(false);
        hold4.setSelected(false);
        hold5.setSelected(false);
        
        //reset dice to 6
        
        
        //disable
        nextGameButton.setEnabled(false);
    }//GEN-LAST:event_nextGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel die1;
    private javax.swing.JLabel die2;
    private javax.swing.JLabel die3;
    private javax.swing.JLabel die4;
    private javax.swing.JLabel die5;
    private javax.swing.JCheckBox hold1;
    private javax.swing.JCheckBox hold2;
    private javax.swing.JCheckBox hold3;
    private javax.swing.JCheckBox hold4;
    private javax.swing.JCheckBox hold5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton nextGameButton;
    private javax.swing.JLabel rollCount;
    private javax.swing.JButton rollDiceButton;
    private javax.swing.JLabel rollLabel;
    // End of variables declaration//GEN-END:variables
}
